# Generated by Django 3.1.8 on 2022-05-20 21:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('linkedin_link', models.URLField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
