# Generated by Django 3.1.8 on 2022-05-21 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 21, 10, 42, 28, 988882, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
