# Generated by Django 3.1.8 on 2022-05-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_feature_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
    ]
