# Generated by Django 3.1.8 on 2022-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='Accuracy', max_length=255),
            preserve_default=False,
        ),
    ]
